name: Update Okteto

on:
  workflow_dispatch:

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    env:
        VENV: venv
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python3 -m venv $VENV
        $VENV/bin/pip3 install --upgrade pip
        $VENV/bin/pip3 install -r requirements.txt
    - name: Run unit tests
      run: |
        $VENV/bin/pytest
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - uses: okteto/namespace@master
      id: okteto
    - uses: docker://pulumi/actions
      with:
        args: up --yes
      env:
        KUBECONFIG: ${{ steps.okteto.outputs.kubeconfig }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
