name: Update Okteto

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pytest
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - uses: okteto/namespace@master
      id: okteto
    - name: Install the Pulumi Open Policy Agent plugin
      uses: docker://pulumi/actions
      with:
        args: plugin install analyzer policy-opa v0.0.2
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
    - name: Deploy using Pulumi
      uses: docker://pulumi/actions
      with:
        args: up --yes
      env:
        KUBECONFIG: ${{ steps.okteto.outputs.kubeconfig }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
