name: Preview changes

on:
  pull_request:
  workflow_dispatch:

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - uses: okteto/namespace@master
        id: okteto
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          KUBECONFIG: ${{ steps.okteto.outputs.kubeconfig }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
